### PR TITLE
Subproblems4subsets

### PR DESCRIPTION
**Pull request by persiflex**
resolves issue #14 by allowing to create subproblems only for some set indices; however, to fully run, requires to solve issue of missing master annotation

### CODE REVIEW

**Comment by guimarqu** [comment]
I think tests should pass because there is no test with a variable/constraint set assigned to master & subproblems.

**Comment by guimarqu** [comment]
> I think tests should pass because there is no test with a variable/constraint set assigned to master & subproblems.

Sorry, there is no need to make the tests passing. I'm going to commit a skeleton of the new `register_decomposition`.

**Comment by guimarqu** [comment]
You should add a test with a dummy model like the one in issue #14 .

**Comment by persiflex** [comment]
Ah, perfect, I was already on the search for the issue.
Okay, I'm going through your changes to understand them and add a dummy model.

**Comment by persiflex** [comment]
I added the tests. However, I noticed that the tests do not solve the optimization since they miss an optimizer. What is the intention behind this?

In fact the model as posted in #14 runs now without throwing the initial error :clap: 
However, it is found infeasible and the centralized machines are not used. 
```
Consumed 0.0 of machine c. Capacity is 1530.
Consumed 0.0 of machine d. Capacity is 1190.
Minimum capacity is 500.
Not all jobs were assigned.
Solution is not feasible. :(
```
Do you have an idea what could be the reason?

**Comment by guimarqu** [comment]
> I added the tests. However, I noticed that the tests do not solve the optimization since they miss an optimizer. What is the intention behind this?

The method `register_decomposition` is called in the hook called by `JuMP.optimize!` and we want to try the decomposition without solving the model.

**Comment by guimarqu** [comment]
> In fact the model as posted in #14 runs now without throwing the initial error 👏
> However, it is found infeasible and the centralized machines are not used.
> 
> ```
> Consumed 0.0 of machine c. Capacity is 1530.
> Consumed 0.0 of machine d. Capacity is 1190.
> Minimum capacity is 500.
> Not all jobs were assigned.
> Solution is not feasible. :(
> ```
> 
> Do you have an idea what could be the reason?

I have no idea. First, you should compute the objective function using the infeasible solution and check if Coluna found the same. If it's the case, the problem may come from the decomposition. Otherwise, it's when the solution is projected from the reformulation to the original vars.

You can print more logs using :
```julia
using Logging
global_logger(ConsoleLogger(stderr, LogLevel(-4)))
```

Please open an issue when you find the bug.

Thank you very much for your contribution to BlockDecomposition !

**Comment by persiflex** [comment]
Alright, thank you for your help!

**Pull request merged**
